name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman.svg
        run: |
          git clone https://github.com/mikhaelle-dev/pacman-generator.git
          cd pacman-generator
          npm install
          npm run build -- --user mikhaelle-dev --output ../dist/pacman.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
