name: Generate Pac-Man Contribution Graph
on:
  schedule:
    - cron: "0 */24 * * *"     # jalan 1x/hari (UTC)
  workflow_dispatch:           # bisa dijalankan manual dari tab Actions

permissions:
  contents: write              # WAJIB: agar bisa push ke branch output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Pac-Man SVG
        run: |
          npm init -y
          npm i pacman-contribution-graph
          mkdir -p dist
          node -e "import('pacman-contribution-graph').then(async m=>{const {render}=m; const fs=require('fs'); const u=process.env.GITHUB_REPOSITORY.split('/')[0]; const light=await render({username:u, theme:'githubLight'}); const dark=await render({username:u, theme:'githubDark'}); fs.writeFileSync('dist/pacman-contribution-graph.svg', light); fs.writeFileSync('dist/pacman-contribution-graph-dark.svg', dark);})"

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
