name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate pacman.svg
        uses: Platane/snk@v3
        with:
          github_user_name: mikhaelle-dev
          outputs: dist/pacman.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pacman
          path: dist/pacman.svg
