name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Update setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: mikhaelle-dev
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
![GitHub Snake Light](https://raw.githubusercontent.com/mikhaelle-dev/mikhaelle-dev/output/github-contribution-grid-snake.svg)
